/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_SIZE 100000000

struct jpeg_in {
	struct {
		u_int in_len;
		char *in_val;
	} in;
};
typedef struct jpeg_in jpeg_in;

struct jpeg_out {
	struct {
		u_int out_len;
		char *out_val;
	} out;
};
typedef struct jpeg_out jpeg_out;

#define DECIMATE_PROG 0x2EAD1234
#define DECIMATE_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define DECIMATE_JPEG 1
extern  jpeg_out * decimate_jpeg_2(jpeg_in *, CLIENT *);
extern  jpeg_out * decimate_jpeg_2_svc(jpeg_in *, struct svc_req *);
extern int decimate_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DECIMATE_JPEG 1
extern  jpeg_out * decimate_jpeg_2();
extern  jpeg_out * decimate_jpeg_2_svc();
extern int decimate_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_jpeg_in (XDR *, jpeg_in*);
extern  bool_t xdr_jpeg_out (XDR *, jpeg_out*);

#else /* K&R C */
extern bool_t xdr_jpeg_in ();
extern bool_t xdr_jpeg_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
