/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_jpeg_in (XDR *xdrs, jpeg_in *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->in.in_val, (u_int *) &objp->in.in_len, MAX_SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_jpeg_out (XDR *xdrs, jpeg_out *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->out.out_val, (u_int *) &objp->out.out_len, MAX_SIZE))
		 return FALSE;
	return TRUE;
}
